### PR TITLE
Better development error messages

### LINKED ISSUE #571: make_audo_md_h throws when an Agenda uses a non-existing WSV
**Describe the bug**
See title.

**To Reproduce**
1. Change the name of an input or output variable in agendas.cc
2. Compile

If applicable, error output:
```
[ 53%] Generating auto_md.h
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
make[3]: *** [src/CMakeFiles/BuildAutoSources.dir/build.make:79: src/auto_md.h] Error 134
make[3]: *** Deleting file 'src/auto_md.h'
make[2]: *** [CMakeFiles/Makefile2:1301: src/CMakeFiles/BuildAutoSources.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3443: python/CMakeFiles/pyarts.dir/rule] Error 2
make: *** [Makefile:1362: pyarts] Error 2
```

**Expected behavior**
An error message stating the offending variable and corresponding agenda.

### PR DESCRIPTION
**Pull request by riclarsson**
The error messages of map::at are not very good.  This works around that by composing and checking the developer errors manually.

When merged, this closes #571

### CODE REVIEW

File: src/agenda_record.cc [hunk 1]
```diff
@@ -238,22 +246,22 @@ void write_agenda_wrapper_header(ofstream& ofs,
   // Wrapper function output parameters
   const ArrayOfIndex& ago = agr.Out();
   ofs << "        // Output\n";
-  for (ArrayOfIndex::const_iterator j = ago.begin(); j != ago.end(); j++) {
+  for (long long j : ago) {
```
Comment (olemke) [inline src/agenda_record.cc:249]: This should be `Index` or `std::int64_t`.

File: src/agenda_record.cc [hunk 2]
```diff
@@ -238,22 +246,22 @@ void write_agenda_wrapper_header(ofstream& ofs,
...
-    ofs << global_data::wsv_data[*j].Name() << ",\n";
+    ofs << wsv_groups[global_data::wsv_data[j].Group()] << "& ";
+    ofs << global_data::wsv_data[j].Name() << ",\n";
   }
 
   // Wrapper function input parameters
   const ArrayOfIndex& agi = agr.In();
   ofs << "        // Input\n";
-  for (ArrayOfIndex::const_iterator j = agi.begin(); j != agi.end(); j++) {
+  for (long long j : agi) {
```
Comment (olemke) [inline src/agenda_record.cc:258]: This should be `Index` or `std::int64_t`.

File: src/agenda_record.cc (hunk 1 above)
Comment (riclarsson) [reply src/agenda_record.cc:249]: Yup.  Argh, clang is messing with me :/
